# Generated by Django 6.1.1 on 2026-09-08 07:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('excerpt', models.CharField(max_length=320, verbose_name='خلاصه')),
                ('category', models.CharField(choices=[('guide', 'راهنمای خرید'), ('beekeeping', 'عسل و زنبورداری'), ('education', 'آموزش زنبورداری'), ('news', 'اخبار و یادداشت')], default='guide', max_length=20, verbose_name='دسته\u200cبندی')),
                ('content', models.TextField(help_text='هر پاراگراف را با یک خط خالی جدا کنید.', verbose_name='محتوا')),
                ('image', models.ImageField(blank=True, null=True, upload_to='posts/', verbose_name='تصویر')),
                ('image_url', models.URLField(blank=True, verbose_name='لینک تصویر (اختیاری)')),
                ('published_at', models.DateField(default=django.utils.timezone.localdate, verbose_name='تاریخ انتشار')),
                ('is_published', models.BooleanField(default=True, verbose_name='منتشر شده')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'پست',
                'verbose_name_plural': 'پست\u200cها',
                'ordering': ['-published_at', '-created_at'],
            },
        ),
    ]
