# Generated by Django 6.1.1 on 2026-09-06 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=80, unique=True)),
                ('name', models.CharField(max_length=150, verbose_name='نام محصول')),
                ('cat', models.CharField(choices=[('single', 'تک\u200cگل'), ('multi', 'چندگیاه'), ('hive', 'فرآورده\u200cهای کندو')], default='single', max_length=10, verbose_name='دسته\u200cبندی')),
                ('weight', models.CharField(help_text='مثلاً «۹۰۰ گرم»', max_length=40, verbose_name='وزن / حجم')),
                ('price', models.PositiveIntegerField(verbose_name='قیمت (تومان)')),
                ('desc', models.TextField(max_length=300, verbose_name='توضیح کوتاه')),
                ('long_description', models.TextField(blank=True, verbose_name='توضیح کامل')),
                ('img', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='تصویر محصول')),
                ('img_url', models.URLField(blank=True, help_text='اگر پر شود، به\u200cجای فایل آپلودی استفاده می\u200cشود.', verbose_name='لینک تصویر (اختیاری)')),
                ('tag', models.CharField(blank=True, max_length=40, verbose_name='برچسب')),
                ('tag_tone', models.CharField(blank=True, choices=[('honey', 'عسلی'), ('olive', 'زیتونی'), ('ember', 'اخگری')], max_length=10, verbose_name='رنگ برچسب')),
                ('highlights', models.TextField(blank=True, help_text='هر خط یک ویژگی برای نمایش در صفحه محصول', verbose_name='ویژگی\u200cها (هر خط یک مورد)')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال / قابل نمایش')),
                ('stock', models.PositiveIntegerField(default=0, verbose_name='موجودی')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'محصول',
                'verbose_name_plural': 'محصولات',
                'ordering': ['-created_at'],
            },
        ),
    ]
